### ISSUE TITLE
Error installing Pyyaml==5.4.1

### ISSUE THREAD

**Issue by Cxiada** [human-3d/Human3D#10]
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
`
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/conda/envs/human3d_cuda113/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/envs/human3d_cuda113/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/envs/human3d_cuda113/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-rjrabh_d/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by aycatakmaz** [comment]
Hi,

This problem is likely due the `Cython` dependencies of the `pyyaml` package.

The following thread could be helpful for solving the issue:
https://github.com/JonasSchult/Mask3D/issues/121

Especially this answer:
https://github.com/JonasSchult/Mask3D/issues/121#issuecomment-1677513350

If the problem still persists, I can recommend you to to take a look at this discussion on the repository of pyyaml, as some other people also seem to have encountered a similar problem:
https://github.com/yaml/pyyaml/issues/724

Let me know if the problem is resolved by following these suggestions!

**Comment by DzigaVertoff** [comment]
> Hi,
> 
> This problem is likely due the `Cython` dependencies of the `pyyaml` package.
> 
> The following thread could be helpful for solving the issue: [JonasSchult/Mask3D#121](https://github.com/JonasSchult/Mask3D/issues/121)
> 
> Especially this answer: [JonasSchult/Mask3D#121 (comment)](https://github.com/JonasSchult/Mask3D/issues/121#issuecomment-1677513350)
> 
> If the problem still persists, I can recommend you to to take a look at this discussion on the repository of pyyaml, as some other people also seem to have encountered a similar problem: [yaml/pyyaml#724](https://github.com/yaml/pyyaml/issues/724)
> 
> Let me know if the problem is resolved by following these suggestions!

Tried that answer, still not working

EDIT:
I solved by creating an empty environment, then I installed cython 0.29.37, then I changed your environment.yaml by upgrading pycocotools to 2.0.7.
Now, inside the conda environment, using `conda env update --file environment.yaml ` it works.

**Comment by aycatakmaz** [comment]
@AT181903 Thank you very much for sharing what solved this problem for you, we will update our README and environment files!
